<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
<script src="<?= $this->baseUrl('/perifer-timePicker-b5195df/jquery.timePicker.js') ?>" type="text/javascript"></script>
<script src="<?= $this->baseUrl('/js/jquery.ui.datepicker-pt-BR.js') ?>" type="text/javascript"></script>
<script src="<?= $this->baseUrl('/perifer-timePicker-b5195df/jquery.timePicker.min.js') ?>" type="text/javascript"></script>
<script src="<?= $this->baseUrl('/js/jquery.timePicker.min.js') ?>" type="text/javascript"></script>
<link rel="stylesheet" href="<?= $this->baseUrl('/perifer-timePicker-b5195df/timePicker.css') ?>">
<link rel="stylesheet" href="<?= $this->baseUrl('/perifer-timePicker-b5195df/timePicker.css') ?>">

<script src="<?= $this->baseUrl('/js/evento.js') ?>"></script>
<style type="text/css">
    .over {
        background-color: paleturquoise;
        color: #000;
    }
</style>
<script type='text/javascript'>
    $(document).ready(function() {
        $('#alerta').hide();
        $("#data_inicial").datepicker($.datepicker.regional['pt-BR']);
        $("#data_final").datepicker($.datepicker.regional['pt-BR']);
        $("#hora1").timePicker();
        $("#hora2").timePicker();
        $("div#profConvidado").hide();
        var dia, mes, ano;
        date = new Date();
        dia = date.getDate();
        mes = date.getMonth() + 1;
        ano = date.getYear() + 1900;
        $("#dia").append(ajeitaData(dia, mes, ano));
    });
    
    function ajeitaData (dia, mes, ano) {
        dia = addZero(dia);
        mes = addZero(mes);
        return dia + "/" + mes + "/" + ano;
    }
    function removerProfessor(id_professor){
        $("tr#"+id_professor).hide('slow',function(){
            $(this).remove();
        });
        //$("tr#"+id_professor).remove();
    }
    function addZero(data) {
        if (data < 10) {
            data = "0" + data;
        }
        return data;
    }
   
   function inserirProfInp(){
      var trs = document.getElementById('tbd').getElementsByTagName('tr');
      var idProfs = "";
        for(var i =0;i<trs.length;i++){
        alert(trs[i].id);
        idProfs+= trs[i].id + '|';
      }
      $('#professoresConvidados').val(idProfs);
   }
    function trocaData(data) {
      
        $("#dia").text(data);
        $('#alerta').hide();
        $('#profConvidado').hide();
        $('#tbd').remove();
        $("table").append("<tbody id=tbd></tbody>");
        
    }
    
    function adicionarProfessor(nome){
                
      /*fornçando o usuario a inserir uma data inicial*/ 
      var dataIni =  $('#data_inicial').val() 
      if(dataIni ==""){
           $("input:text:eq(1):visible").focus();
           $('#alerta').show('slow');
          return;
      }
      else{
         $("#dia").text(dataIni);  
      }
      
       var professores = new Array();
        <? foreach ($this->lista as $idProfessor => $nomeProfessor) {
            echo 'professores[' . $idProfessor . '] = "' . $nomeProfessor . '";';
        }?>
        for (var x in professores) {
            if (professores[x] == nome) {

               //var tag =$("tr#"+x).val();
               var tag = $("#tbd:has(tr#"+x+")").val();
              
               if(tag==undefined){
                    
                var Eventos = new EventosT();
                $.ajax({
                    url: '<?=$this->baseUrl('/professor/get-eventos/id/') ?>' + x,
                    context: this,
                    async: false,
                    success: function(data) {
                        var profEventos = new Array();
                        var eventos = data.split("<->");
                        for (var y in eventos) {
                            var evento = eventos[y].split("|");
                            var i = 0;
                            var eve = new Evento();
                            eve.setIdEvento(evento[i++]);
                            eve.setTitulo(evento[i++]);
                            eve.setDataInicial(evento[i++]);
                            eve.setDataFinal(evento[i++]);
                            eve.setHora1(evento[i++]);
                            eve.setHora2(evento[i++]);
                           
                            Eventos.addEvento(eve);
                            profEventos[y] = eve;
                        }
                        professores[x].eventos = profEventos;
                        //alert(professores[x].eventos);
                    }
                });
                
                var isHiden = true;
                if (isHiden) {
                    $("div#profConvidado").css({'overflow' : 'scroll', 'width' : '850px'});
                    $("div#profConvidado").show();
                    isHiden = false;
                }
                
                var professor = '<tr id="'+x+'"><td><a onclick="removerProfessor('+x+')" class="button red small" title="Remover professor">X</a></td><td>' + nome + '</td>';
                for (var j = 0; j < 24; j++) {
                    var horaCorreta = addZero(j);
                    professor += '<td id="' + x + '-' + horaCorreta + '"></td>';
                }
                professor += '</tr>';
                $("table tbody").append(professor);
                
                var titulo;
                for (var index in Eventos.eventos) {
                    var horas, hora, minutos = 0;
                    titulo=Eventos.eventos[index].titulo;
                    if (getMinuto(Eventos.eventos[index].hora2) > 2) {
                        minutos = 1;
                    }
                    
                    // se a hora inicial e final eh no mesmo dia
                    if (Eventos.eventos[index].dataInicial == $("#dia").text() && 
                        Eventos.eventos[index].dataFinal == $("#dia").text()) {
                        
                        horas = getHoraInt(Eventos.eventos[index].hora2) - getHoraInt(Eventos.eventos[index].hora1);
                        horas += minutos;
                        hora = parseInt(getHoraInt(Eventos.eventos[index].hora1));
                        
                    // se o evento começar no dia
                    } else if (Eventos.eventos[index].dataInicial == $("#dia").text() &&
                        Eventos.eventos[index].dataFinal != $("#dia").text()) {
                        
                        horas = 24 - getHora(Eventos.eventos[index].hora1);
                        hora = parseInt(getHoraInt(Eventos.eventos[index].hora1));
                    
                    // se o evento terminar no dia
                    } else if (Eventos.eventos[index].dataInicial != $("#dia").text() &&
                        Eventos.eventos[index].dataFinal == $("#dia").text()) {

//                        alert( Eventos.eventos[index].dataFinal)
//                        var id = '"#' + x + '-' + getHora(Eventos.eventos[index].hora1) + ':00:00"';
//                        alert(id);

                        
                        horas = getHoraInt(Eventos.eventos[index].hora2);
                        horas += minutos;
                        hora = 0;

                        
                    }
                    
                    for (var abc = 0; abc < horas; abc++) {
                        var soma = hora + abc
                        var id = '#' + x + '-' + addZero(soma);
                        //alert(id);
                        $(id).addClass('over');
                        $(id).text(titulo);
                       // $("#2-10:00:00").addClass('over');
                       // $(id).css("background-color", "red");

                   }
                    
                }
                break;
             }
             else{
             
             alert("Este professor já está na lista!");
             }
            }
        }
   }
</script>

<script type='text/javascript'>
    $(function() {
        var availableTags = [<?$virgula = false; foreach ($this->lista as $idProfessor => $nomeProfessor) {
                     if ($virgula == false) {
                        echo '"' . $nomeProfessor . '"';
                        $virgula = true;
                     } else {
                        echo ', "' . $nomeProfessor . '"';
                     }
                    }?>];

		$("#convidados").autocomplete({
			source: availableTags
		});
	});
</script>

<form method="POST" action="<?= $this->baseUrl('agenda/add-evento') ?>">
    <div style="margin-left: 5%;width: 50%">
        Descrição do evento:  <input id="titulo" name="titulo" class="i-format" type="text" /><p/>
        Data Inicial :<input class="subscr_email" id="data_inicial" name="data_inicial" type="text" onblur="trocaData($('#data_inicial').val())" /><div style="color: red;margin-left: 350px;"  id="alerta">Para adicionar um professor você devera selecionar uma data inicial.</div><p/>
        Data Final   :<input class="subscr_email" id="data_final" name="data_final" type="text" /><p/>
        Hora Inicial:  <input name="hora1"  class="subscr_email" type="text" id="hora1"  size="5" maxlength="5" /><p/>
        Hora Final:  <input name="hora2" class="subscr_email"  type="text" id="hora2"   size="5" maxlength="5" /><p/>
        Privacidade: <input id="privado" name="privado" type="radio" value="publico" checked />Público <input id="privado" name="privado" type="radio" value="privado" />Privado
        <br /><br />
        Adicionar convidado: <input id="convidados" type="text" class="i-format" /><a onclick="adicionarProfessor($('#convidados').val())" class="button">Adicionar</a><p/>
        <div id="profConvidado">
            <center><h3 id="dia"></h3></center>
            <table>
                <thead>
                    <tr>
                        <td colspan="2"></td>
                        
                        <? for ($i = 0; $i < 24; $i++) {
                            if ($i < 10) {
                                $j = '0' . $i;
                            } else {
                                $j = $i;
                            }
                            echo '<td id="' . $j . ':00:00">' . $j . ':00</td>';
                        } ?>
                    </tr>
                </thead>
                <tbody id="tbd">
                </tbody>
            </table>
        </div>
        
    </div>
    <br />
    
    <INPUT style="margin-left: 5%;" TYPE="submit" VALUE="Cadastrar evento" onclick="inserirProfInp()" class="button orange large">
     <input  id="professoresConvidados" name="professoresConvidados" value="" type="hidden"  />
      
 </form>
