<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
<script src="<?= $this->baseUrl('/perifer-timePicker-b5195df/jquery.timePicker.js') ?>" type="text/javascript"></script>
<script src="<?= $this->baseUrl('/perifer-timePicker-b5195df/jquery.timePicker.min.js') ?>" type="text/javascript"></script>
<link rel="stylesheet" href="<?= $this->baseUrl('/perifer-timePicker-b5195df/timePicker.css') ?>">
<script>
    $(document).ready(function() {
        $("#data_inicial").datepicker();
    });
    $(document).ready(function() {
        $("#data_final").datepicker();
    });
    $(document).ready(function() {
        $("#hora1").timePicker();
    });
    $(document).ready(function() {
        $("#hora2").timePicker();
    });
    
   function adicionarProfessor(nome){
         alert('as');
//          var array = new Array();
//          array.push(nome);
//          for(i=0;i<array.length;i++){
//               document.getElementById("profConvidado").innerHTML=array[i];
//          }
        
    }
</script>

<script>
	$(function() {
	
 var availableTags =[<?$virgula = false; for($index=0;$index<count($this->lista);$index++) {
                     if ($virgula == false) {
                        echo $this->lista[$index];
                        $virgula = true;
                     } else {
                        echo ", " . $this->lista[$index];
                     }
                    }?>];
                      
		$( "#convidados" ).autocomplete({
			source: availableTags
		});
	});
       
	</script>

<form method="POST" action="<?= $this->baseUrl('agenda/add-evento') ?>">
    <div style="margin-left: 25%;width: 50%">
        Descrição do evento:  <input id="titulo" name="titulo" class="i-format" type="text" /><p/>
        Data Inicial :<input class="subscr_email" id="data_inicial" name="data_inicial" type="text" /><p/>
        Data Final   :<input class="subscr_email" id="data_final" name="data_final" type="text" /><p/>
        Hora Inicial:  <input name="hora1"  class="subscr_email" type="text" id="hora1"  size="5" maxlength="5"><p/>
        Hora Final:  <input name="hora2" class="subscr_email"  type="text" id="hora2"   size="5" maxlength="5"><p/>
        Adicionar convidado:<input id="convidados" type="text" class="i-format"/>
        <a href="#" class="button">Adicionar</a>
    </div> 
   <INPUT style="margin-left: 25%;"  TYPE="submit" VALUE="Cadastrar evento"  class="button white large">
   
 </form>
        




   





