<div class=""><p><a href="<?= $this->baseUrl('/agenda/adicionar/') ?>">Adicionar</a><a href="<?= $this->baseUrl('/agenda/editar     /') ?>">Adicionar</a></p></div>
<div id='calendar'></div>
     <?= $cont = count($this->listaEventos['anoInicio']);?>
 
    <? for ($i = 0; $i<$cont; $i++):?>
    
    <?$anoIni = $this->listaEventos['anoInicio'][$i];?> 
    <?$anoFim = $this->listaEventos['anoFim'][$i];?> 
    <?$mesIni = $this->listaEventos['mesInicio'][$i];?> 
    <?$mesFim = $this->listaEventos['mesFim'][$i];?> 
    <?$horaIni = $this->listaEventos['horaInicio'][$i];?>
    <?$horaFim = $this->listaEventos['horaFim'][$i];?>
    <?$mimIni = $this->listaEventos['minutoInicio'][$i];?>
    <?$mimFim = $this->listaEventos['minutoFim'][$i];?>
      <?$titulo = $this->listaEventos['titulo'][$i];?>
<?=var_dump($mesIni)?>
<script type='text/javascript'>

	$(document).ready(function() {
	
		var date = new Date();
		var d = date.getDate();
		var m = date.getMonth();
		var y = date.getFullYear();
		
		var calendar = $('#calendar').fullCalendar({
			header: {
				left: 'prev,next today',
				center: 'title',
				right: 'month,agendaWeek,agendaDay'
			},
			selectable: true,
			selectHelper: true,
			select: function(start, end, allDay) {
				var title = prompt('Event Title:');
				if (title) {
					calendar.fullCalendar('renderEvent',
						{
							title: title,
							start: start,
							end: end,
							allDay: allDay
						},
						true // make the event "stick"
					);
				}
				calendar.fullCalendar('unselect');
			},
			editable: true,
			events: [
				
				{
					title: '<?=$titulo?>',
					start: new Date(y, m, 28),
					end: new Date(y, m, 29),
					url: 'http://google.com/'
                                       
				},
			]
		});
		
	});

</script>

 <? endfor; ?> 

<style type='text/css'>

	body {
		margin-top: 40px;
		text-align: center;
		font-size: 14px;
		font-family: "Lucida Grande",Helvetica,Arial,Verdana,sans-serif;
		}

	#calendar {
		width: 900px;
		margin: 0 auto;
		}


</style>
