 <section class="container">
                            <div class="top">
                                <!--					<a class="logo" href="./index.html">Gestão de disponibilidade</a>-->
                                <nav id="horizontal">
                                    <ul id="nav">
                                                                   
                                        </li>
                                        <li><a href="<?= $this->baseUrl('/equipamento/index/') ?>">Equipamentos</a><span></span></a>
                                        </li>
                                        <li>
                                        <a href="<?= $this->baseUrl('secretaria/index') ?>">Salas</a><span></span></a>
                                        </li>
                                        <li>
                                         <a href="<?= $this->baseUrl('tipo-sala/index') ?>">Tipos de Salas</a><span></span></a>
                                        </li>                              


                                    </ul>
                                </nav><!-- End of menu -->
                            </div>
                        </section>
			
				<div class="grid_12 placeslider">
					
					<div class="clear"></div>
				</div>
				
				
				
				
				
				