<p><a href="<?= $this->baseUrl('/disciplina/cadastrar-disciplina') ?>">Cadastrar Disciplina</a></p>
<table class="style2"> 
    <thead> 
        <tr> 
            <th>Codigo</th>
            <th>Nome</th>
            <th>Ementa</th>
            <th>Carga Horaria</th>
        </tr> 
    </thead> 
    <tbody> 
        <? foreach ($this->listarTodos as $item): ?> 
            <tr> 
                <td><?= $item->getId_disciplina() ?></td> 
                <td><?= $item->getCodigo() ?></td>
                <td><?= $item->getNome() ?></td>
                <td><?= $item->getEmenta() ?></td>
                <td><?= $item->getCargaHoraria() ?></td>
                <td>
                    <a href="<?= $this->baseUrl('/disciplina/editar-disciplina/id_disciplina/') ?><?= $item->getId_disciplina() ?>">Editar</a>
                </td>
                <td>
                    <a href="<?= $this->baseUrl('/disciplina/remover-disciplina/id_disciplina/') ?><?= $item->getId_disciplina() ?>">Remover</a>
                </td>
            </tr>
        <? endforeach; ?>
    </tbody>
</table>