<form method="post" action="<?= $this->baseUrl('/professor/nivel-interesse/')?>" >

 
<table class="style2">  
    <thead> 
        <tr> 
            <th>Codigo</th>
            <th>Nome</th>
            <th>Ementa</th>
            <th>Nivel de interesse(1 a 5)</th>
 
        </tr> 
    </thead> 
    <tbody> 
        <? foreach ($this->listarTodos as $item): ?> 
            <tr> 

                <td><?= $item->getCodigo() ?></td>
                <td><?= $item->getNome() ?></td>
                <td><?= $item->getEmenta() ?></td>
                <td>
                        <input type="text" id="<?= $item->getCodigo() ?>" name="<?= $item->getCodigo() ?>">
                        <br/>
<!--                        <INPUT  id="enviar" TYPE="submit" VALUE="Salvar" class="button blue small">      
               
                </td>-->
                
            </tr>
        <? endforeach; ?>
    </tbody>
</table>

<INPUT TYPE="submit" VALUE="Cadastrar Dados" class="button black xlarge">

</form>