<form method="post" action="<?= $this->baseUrl('/professor/nivel-interesse/')?>" >

 
<table class="style2">  
    <thead> 
        <tr> 
            <th>Codigo</th>
            <th>Nome</th>
            <th>Ementa</th>
            <th>Nivel de interesse</th>
 
        </tr> 
    </thead> 
    <tbody> 
        <? foreach ($this->listarTodos as $item): ?> 
            <tr> 

                <td><?= $item->getCodigo() ?></td>
                <td><?= $item->getNome() ?></td>
                <td><?= $item->getEmenta() ?></td>
                <td>
<!--                        <input type="text" id="" name="<?= $item->getCodigo() ?>">-->
                      
                    <input type="radio" name="<?= $item->getCodigo() ?>" value="1" /> 1<br />
                       <input type="radio" name="<?= $item->getCodigo() ?>" value="2" /> 2<br />
                       <input type="radio" name="<?= $item->getCodigo() ?>" value="3" /> 3<br />
                       <input type="radio" name="<?= $item->getCodigo() ?>" value="4" /> 4<br />
                       <input type="radio" name="<?= $item->getCodigo() ?>" value="5" /> 5<br />
                        <br/>
<!--                        <INPUT  id="enviar" TYPE="submit" VALUE="Salvar" class="button blue small">      
               
                </td>-->
                
            </tr>
        <? endforeach; ?>
    </tbody>
</table>

<INPUT TYPE="submit" VALUE="Cadastrar Dados" class="button black xlarge">

</form>