<nav id="horizontal">
    <ul id="nav">

        <li>
            <a href="<?= $this->baseUrl('login/sair/') ?>">Sair</a><span></span></a>
        </li>


    </ul>
</nav>

<p><a class="button orange" href="<?= $this->baseUrl('/curso/adicionar-curso/') ?>">Adicionar Curso</a></p>

<table class="style2"> 
    <thead> 
        <tr> 
            <th>Código</th>
            <th>Nome</th>
            <th colspan="2">Ação</th>
           
            
        </tr> 
    </thead> 
    <tbody> 
        <? foreach ($this->listarTodos as $item): ?> 
            <tr> 
                <td><?= $item->getCodigo() ?></td> 
                <td><?= $item->getNome() ?></td>
                
                
                <td>
                    <a class="button green small" href="<?= $this->baseUrl('/curso/editar-curso/id_curso/') ?><?= $item->getId_curso() ?>">Editar</a>
                </td>
                <td>
                    <a class="button red small" href="<?= $this->baseUrl('/curso/remover-curso/id_curso/') ?><?= $item->getId_curso() ?>">Remover</a>
                </td>
            </tr>
        <? endforeach; ?>   
    </tbody>
</table>
