

<p><a href="<?= $this->baseUrl('/curso/adicionar-curso/') ?>">Adicionar Equipamento</a></p>

<table class="style2"> 
    <thead> 
        <tr> 
            <th>Nome</th>
            <th>Codigo</th>
            <th colspan="2">Ação</th>
        </tr> 
    </thead> 
    <tbody> 
        <? foreach ($this->listarTodos as $item): ?> 
            <tr> 
                <td><?= $item->getId_curso() ?></td> 
                <td><?= $item->getNome() ?></td>
                <td><?= $item->getCodigo() ?></td>
                <td>
                    <a href="<?= $this->baseUrl('/curso/editar-curso/id_curso/') ?><?= $item->getId_curso() ?>">Editar Curso</a>
                </td>
                <td>
                    <a href="<?= $this->baseUrl('/curso/remover-curso/id_curso/') ?><?= $item->getId_curso() ?>">Remover Curso</a>
                </td>
            </tr>
        <? endforeach; ?>
    </tbody>
</table>
