<div style="margin-top: -30px;margin-left: 600px;text-align: center;border: 1 px solid black;width: 300px;height: 25px; border-radius: 5px;background-color: black;color: white "><?=$this->identity->nome?></div>
<nav id="horizontal">
    <ul id="nav">

        <li>
            <a href="<?= $this->baseUrl('login/sair/') ?>">Sair</a><span></span></a>
        </li>


    </ul>
</nav>

<!--<p><a href="<?= $this->baseUrl('/curso/adicionar-curso/') ?>">Adicionar Curso</a></p>-->

<table class="style2"> 
    <thead> 
        <tr> 
            <th>Código</th>
            <th>Nome</th>
            <th colspan="2">Ação</th>
           
            
        </tr> 
    </thead> 
    <tbody> 
        <? foreach ($this->listarTodos as $item): ?> 
            <tr> 
                <td><?= $item->getCodigo() ?></td> 
                <td><?= $item->getNome() ?></td>
                
                
                <td>
                    <a class="button blue small" href="<?= $this->baseUrl('/curso/disciplina/'.$item->getId_curso()) ?>">Ver lista de disciplinas</a>
                </td>
            </tr>
        <? endforeach; ?>
    </tbody>
</table>
