
<div style="margin-left: 300px;margin-top: 30px">
    
<b style="font-size: 20px;margin-left: -60px;">Login: </b>
</div>
<hr style="width: 500px;margin-left: 250px;background: lightgrey">
<div style="margin-left: 200px;margin-top: 20px">

<p/>

<?=$this->login?>



</div>
<div style="margin-top: -57px;margin-left: 430px"><b>Esqueceu sua senha?</b> <a href="<?=$this->baseUrl('recuperar/senha');?>">Clique aqui</a></div>
<div style="margin-top: 20px;margin-left: 450px;font-size: 15px; color: tomato"><?=$this->error;?></div>
<div style="margin-top: 60px;margin-left: 400px"></div>
<hr style="margin-top: 20px;height: 6px;width: 800px;margin-left: 70px;background: lightsteelblue">