 <section class="container">
                            <div class="top">
                                <!--					<a class="logo" href="./index.html">Gestão de disponibilidade</a>-->
                                <nav id="horizontal">
                                    <ul id="nav">
                                                                   
                                        </li>
                                        <li><a href="<?= $this->baseUrl('/equipamento/index/') ?>">Equipamentos</a><span></span></a>
                                        </li>
                                        <li>
                                        <a href="<?= $this->baseUrl('secretaria/index') ?>">Salas</a><span></span></a>
                                        </li>
                                        <li>
                                         <a href="<?= $this->baseUrl('tipo-sala/index') ?>">Tipos de Salas</a><span></span></a>
                                        </li>                              


                                    </ul>
                                </nav><!-- End of menu -->
                            </div>
                        </section>

<a class="button orange small" href="<?= $this->baseUrl('/equipamento/adicionar-equipamento/') ?>">Adicionar Equipamento</a>
<table class="style2"> 
    <thead> 
        <tr> 
            <th>Identificador</th>
            <th>Descrição</th>
            <th colspan="2">Ação</th>
        </tr> 
    </thead> 
    <tbody> 
        <? foreach ($this->listaEquipamentos as $item): ?> 
            <tr> 
                <td><?= $item->getId_equipamento() ?></td> 
                <td><?= $item->getDescricao() ?></td>
                <td>
                    <a class="button green small" href="<?= $this->baseUrl('/equipamento/editar-equipamento/id_equipamento/') ?><?= $item->getId_equipamento() ?>">Editar</a>
                </td>
                <td>
                    <a class="button red small" href="<?= $this->baseUrl('/equipamento/remover-equipamento/id_equipamento/') ?><?= $item->getId_equipamento() ?>">Remover</a>
                </td>
            </tr>
        <? endforeach; ?>
    </tbody>
</table>
