<nav id="horizontal">
    <ul id="nav">

        <li>
            <a href="<?= $this->baseUrl('login/sair/') ?>">Sair</a><span></span></a>
        </li>


    </ul>
</nav>
<p> 
<a class="button orange" href="<?= $this->baseUrl('/equipamento/adicionar-equipamento/') ?>">Adicionar Equipamento</a>
<a class="button orange" href="<?= $this->baseUrl('/cadastros/') ?>">Voltar</a></p>
<table class="style2"> 
    <thead> 
        <tr> 
            <th>Identificador</th>
            <th>Descrição</th>
            <th colspan="2">Ação</th>
        </tr> 
    </thead> 
    <tbody> 
        <? foreach ($this->listaEquipamentos as $item): ?> 
            <tr> 
                <td><?= $item->getId_equipamento() ?></td> 
                <td><?= $item->getDescricao() ?></td>
                <td>
                    <a class="button green small" href="<?= $this->baseUrl('/equipamento/editar-equipamento/id_equipamento/') ?><?= $item->getId_equipamento() ?>">Editar</a>
                </td>
                <td>
                    <a class="button red small" href="<?= $this->baseUrl('/equipamento/remover-equipamento/id_equipamento/') ?><?= $item->getId_equipamento() ?>">Remover</a>
                </td>
            </tr>
        <? endforeach; ?>
    </tbody>
</table>
