<div style="margin-top: -30px;margin-left: 600px;text-align: center;border: 1 px solid black;width: 300px;height: 25px; border-radius: 5px;background-color: black;color: white "><?=$this->identity->nome?></div>
<nav id="horizontal">
    <ul id="nav">

        <li>
            <a href="<?= $this->baseUrl('login/sair/') ?>">Sair</a><span></span></a>
        </li>


    </ul>
</nav>
<p><a class="button orange" href="<?= $this->baseUrl('/tipo-sala/cadastrar-tipo-sala') ?>">Cadastrar Categoria de Sala</a>
<a class="button orange" href="<?= $this->baseUrl('/cadastros/') ?>">Voltar</a>
</p>
<table class="style2"> 
    <thead> 
        <tr> 

            <th>Descrição</th>
            <th colspan=2>Ação</th>
        </tr> 
    </thead> 
    <tbody> 
        <? foreach ($this->listaTipoSala as $item): ?> 
            <tr> 

                <td><?= $item->getDescricao() ?></td>
                <td>
                    <a class="button green small" href="<?= $this->baseUrl('/tipo-sala/editar-tipo-sala/id_tipo_sala/') ?><?= $item->getId_tipo_sala() ?>">Editar</a>
                </td>
                <td>
                    <a class="button red small" href="<?= $this->baseUrl('/tipo-sala/remover-tipo-sala/id_tipo_sala/') ?><?= $item->getId_tipo_sala() ?>">Remover</a>
                </td>
            </tr>
        <? endforeach; ?>
    </tbody>
</table>