
<table class="style2"> 
    <thead> 
        <tr> 
            <th>Número</th> 
            <th>Descrição</th> 
            <th>Capacidade</th> 
            <th>Tipo</th> 
            <th>Informações adicionais</th>
            <th>Status</th>
            <th>Tipo de sala</th>
            <th>Responsável</th>
            <th>Ação</th>
        </tr> 
    </thead> 
    <? foreach ($this->listaSalas as $item): ?> 
        <tbody> 
            <tr> 
                <td><?= $item->getNumero() ?></td> 
                <td><?= $item->getDescricao() ?></td> 
                <td><?= $item->getCapacidade() ?></td> 
                <td><?= $item->getCapacidade_desc() ?></td>
                <td><?= $item->getInfo_adicionais() ?></td> 
                <td><?= $item->getStatus_disponibilidade() ?></td>
                <td><?= $item->getInfo_adicionais() ?></td> 
                <td><?= $item->getResponsavel() ?></td> 
                <td>
                    <a href="<?= $this->baseUrl('/secretaria/editar-sala/') ?><?= $item->getNumero() ?>">Editar</a>
                </td>
            </tr>
        </tbody>
    <? endforeach; ?>
</table>

