<section class="container">
    <div class="top">
        <!--					<a class="logo" href="./index.html">Gestão de disponibilidade</a>-->
        <nav id="horizontal">
            <ul id="nav">

                </li>
                <li><a href="<?= $this->baseUrl('/equipamento/index/') ?>">Equipamentos</a><span></span></a>
                </li>
                <li>
                    <a href="<?= $this->baseUrl('secretaria/index') ?>">Salas</a><span></span></a>
                </li>
                <li>
                    <a href="<?= $this->baseUrl('tipo-sala/index') ?>">Tipos de Salas</a><span></span></a>
                </li>                              


            </ul>
        </nav><!-- End of menu -->
    </div>
</section>
<div class=""><p><a href="<?= $this->baseUrl('/secretaria/adicionar-sala/') ?>">Adicionar Sala</a></p></div>
<table class="style2"> 
    <thead> 
        <tr> 
            <th>Número</th> 
            <th>Tipo de sala</th>
            <th>Descrição</th> 
            <th>Capacidade </th> 
            <th>Tipo</th> 
            <th>Informações adicionais</th>
            <th>Status</th>
            <th>Responsável</th>
            <th colspan="2">Ação</th>
        </tr> 
    </thead> 
    <? foreach ($this->listaSalas as $item): ?> 
        <tbody> 
            <tr> 
                <td><?= $item->getNumero() ?></td> 
                <td><?= $item->getId_tipo_sala() ?></td> 
                <td><?= $item->getDescricao() ?></td> 
                <td><?= $item->getCapacidade() ?></td> 
                <td><?= $item->getCapacidade_desc() ?></td>
                <td><?= $item->getInfo_adicionais() ?></td> 
                <td><?= $item->getStatus_disponibilidade() ?></td>
                <td><?= $item->getResponsavel() ?></td> 
                <td>
                    <a href="<?= $this->baseUrl('/secretaria/editar-sala/') ?><?= $item->getNumero() ?>">Editar</a>
                </td>
                <td>
                    <a href="<?= $this->baseUrl('/secretaria/remover-sala/id_sala/') ?><?= $item->getNumero() ?>">Remover</a>
                </td>
            </tr>
        </tbody>
    <? endforeach; ?>
</table>

