<script type='text/javascript' src="<?= $this->baseUrl('/js/horario/curso.js') ?>" ></script>
<script type='text/javascript' src="<?= $this->baseUrl('/js/horario/periodo-letivo.js') ?>" ></script>
<script type='text/javascript' src="<?= $this->baseUrl('/js/horario/turma.js') ?>" ></script>
<script type='text/javascript' src="<?= $this->baseUrl('/js/horario/disciplina.js') ?>" ></script>
<script type='text/javascript' src="<?= $this->baseUrl('/js/horario/professor.js') ?>" ></script>
<script type='text/javascript'>
    $(document).ready(function() {
        getCursos('<?= $this->baseUrl('/horario/get-cursos/') ?>', '#cursos');
        getPeriodosLetivos('<?= $this->baseUrl('/horario/get-periodos-letivos/') ?>', '#periodosLetivos');
        getTurmas('<?= $this->baseUrl('/horario/get-turmas/') ?>', '#turmas');
    });
    
    function getDisciplinasCurso() {
        $('#disciplinas').empty();
        $('#disciplinas').append('<option label="" selected="selected" value=""></option>');
        var idCurso = $('#cursos').val();
        getDisciplinasByCurso('<?= $this->baseUrl('/horario/get-disciplinas/curso/') ?>', '#disciplinas', idCurso);
    }
    
    function getProfessoresNI() {
        $('#professores').empty();
        $('#professores').append('<option label="" selected="selected" value=""></option>');
        var idDisciplina = $('#disciplinas').val();
        getProfessores('<?= $this->baseUrl('/horario/get-professores/disciplina/') ?>', '#professores', idDisciplina);
    }
</script>
<form>
    <div id="selects" >
        <label>Período Letivo:</label><select id="periodosLetivos" title="Período Letivo" ><option label="" selected="selected" value=""></option></select>
        <label>Curso:</label><select id="cursos" title="Curso" onchange="getDisciplinasCurso()"><option label="" selected="selected" value=""></option></select>
        <label>Turma:</label><select id="turmas" title="Turma" ><option label="" selected="selected" value=""></option></select>
        <label>Disciplina:</label><select id="disciplinas" title="Disciplina" onclick="getProfessoresNI()"><option label="" selected="selected" value=""></option></select>
        <label>Professor:</label><select id="professores" title="Professor" ><option label="" selected="selected" value=""></option></select>
    </div>
    <div id="horarios" >
        <table>
            <thead>
                <tr>
                    <td></td>
                    <td id="segunda">Segunda</td>
                    <td id="terca">Terça</td>
                    <td id="quarta">Quarta</td>
                    <td id="quinta">Quinta</td>
                    <td id="sexta">Sexta</td>
                    <td id="sabado">Sábado</td>
                </tr>
            </thead>
            <tbody>
                <?
                foreach ($this->horas as $hora) {
                    echo '<tr id="' . $hora . '"><td>' . $hora . '</td>';
                    foreach ($this->dias as $dia) {
                        echo '<td id="' . $dia . '-' . $hora . '"></td>';
                    }
                    echo '</tr>';
                }
                ?>
            </tbody>
        </table>
    </div>
</form>