<script type='text/javascript' src="<?= $this->baseUrl('/js/horario/curso.js') ?>" ></script>
<script type='text/javascript' src="<?= $this->baseUrl('/js/horario/periodo-letivo.js') ?>" ></script>
<script type='text/javascript' src="<?= $this->baseUrl('/js/horario/turma.js') ?>" ></script>
<script type='text/javascript' src="<?= $this->baseUrl('/js/horario/disciplina.js') ?>" ></script>
<script type='text/javascript' src="<?= $this->baseUrl('/js/horario/professor.js') ?>" ></script>
<script type='text/javascript' src="<?= $this->baseUrl('/js/horario/disponibilidade-aula.js') ?>" ></script>
<script type='text/javascript' src="<?= $this->baseUrl('/js/horario/horario.js') ?>" ></script>
<script type='text/javascript' src="<?= $this->baseUrl('/js/json2.js') ?>" ></script>
<script type='text/javascript'>
    $(document).ready(function() {
        getCursos('<?= $this->baseUrl('/horario/get-cursos/') ?>', '#cursos');
        getPeriodosLetivos('<?= $this->baseUrl('/horario/get-periodos-letivos/') ?>', '#periodosLetivos');
        getTurmas('<?= $this->baseUrl('/horario/get-turmas/') ?>', '#turmas');
    });
    
    function getDisciplinasCurso() {
        cleanSelect('#disciplinas');
        cleanSelect('#professores');
        clean();
        var idCurso = $('#cursos').val();
        getDisciplinasByCurso('<?= $this->baseUrl('/horario/get-disciplinas/curso/') ?>', '#disciplinas', idCurso);
    }
    
    function getProfessoresNI() {
        cleanSelect('#professores');
        clean();
        var idDisciplina = $('#disciplinas').val();
        getProfessores('<?= $this->baseUrl('/horario/get-professores/disciplina/') ?>', '#professores', idDisciplina);
    }
    
    function getDisponibilidades() {
        var idProfessor = $('#professores').val();
        clean();
        getDisponibilidadeProfessor('<?= $this->baseUrl('/horario/get-disponibilidade-professor/professor/') ?>', idProfessor);
    }
    
    function cleanColors(select) {
        $.each(select, function() {
            $("#" + this).removeClass('disp');
            $("#" + this).removeClass('marc');
        });
    }
    
    function cleanText(select) {
        $.each(select, function() {
            $("#" + this).empty();
        });
    }
    
    function cleanSelect(select) {
        $(select).empty();
        $(select).append('<option label="" selected="selected" value=""></option>');
    }
    
    function clean() {
        var diasHoras = [<?
$dh = true;
foreach ($this->horas as $hora) {
    foreach ($this->dias as $dia) {
        if ($dh) {
            echo '"' . $hora . '-' . $dia . '"';
            $dh = false;
        } else {
            echo ', "' . $hora . '-' . $dia . '"';
        }
    }
}
?>];
            cleanColors(diasHoras);
            cleanText(diasHoras);
        }
        
        function marcarHorario(seletor) {
            $("#" + seletor).removeClass('disp');
            $("#" + seletor).removeClass('marc');
            //$("#" + seletor).addClass('marc');
            $("#" + seletor).append('<img src="<?= $this->baseUrl('/images/loading.gif') ?>" />');
            $("#" + seletor).append('<img src="<?= $this->baseUrl('/images/gato.gif') ?>" />');
            
            var horario = new Horario();
            horario.curso = $('#cursos').val();
            horario.dia = extractDia(seletor);
            horario.disciplina = $('#disciplinas').val();
            horario.periodoLetivo = $('#periodosLetivos').val();
            horario.turma = $('#turmas').val();
            horario.horaFinal = extractHora(seletor);
            horario.horaInicial = extractHora(seletor);
            var professor = $('#professores').val();
            horario.addProfessor(professor);
            
            addHorario('<?= $this->baseUrl('/horario/add-horario/') ?>', seletor, horario);
        }
        
        function extractDia(seletor) {
            var dia = seletor.split("-");
            return dia[1];
        }
        function extractHora(seletor) {
            var dia = seletor.split("-");
            return dia[0];
        }
</script>
<style type="text/css">
    .disp {
        background-color: greenyellow;
    }
    .marc {
        background-color: #ff9a22;
    }
    .legenda {
        margin-left: 80%;
        margin-top: -8%;
    }
</style>
<form>
    <div>
    <div id="selects" >
        <label>Período Letivo:</label><select id="periodosLetivos" title="Período Letivo" ><option label="" selected="selected" value=""></option></select>
        <label>Curso:</label><select id="cursos" title="Curso" onchange="getDisciplinasCurso()"><option label="" selected="selected" value=""></option></select>
        <label>Turma:</label><select id="turmas" title="Turma" ><option label="" selected="selected" value=""></option></select><br /><br />
        <label>Disciplina:</label><select id="disciplinas" title="Disciplina" onchange="getProfessoresNI()"><option label="" selected="selected" value=""></option></select>
        <label>Professor:</label><select id="professores" title="Professor" onchange="getDisponibilidades()"><option label="" selected="selected" value=""></option></select>
    </div>
    <div class="legenda">Legenda: <div class="disp" style="height: 25px; width: 150px;">Horário disponível</div><div class="marc" style="height: 25px; width: 150px;">Horário já marcado</div></div>
    </div><br /><hr />
    <div id="horarios" >
        <table>
            <thead>
                <tr>
                    <th width="4%"></th>
                    <th width="14%" id="segunda">Segunda</th>
                    <th width="14%" id="terca">Terça</th>
                    <th width="14%" id="quarta">Quarta</th>
                    <th width="14%" id="quinta">Quinta</th>
                    <th width="14%" id="sexta">Sexta</th>
                    <th width="14%" id="sabado">Sábado</th>
                </tr>
            </thead>
            <tbody>
                <?
                foreach ($this->horas as $hora) {
                    echo '<tr id="' . $hora . '"><th>' . $hora . ':30</th>';
                    foreach ($this->dias as $dia) {
                        echo '<td id="' . $hora . '-' . $dia . '" onclick="marcarHorario(this.id)"></td>';
                    }
                    echo '</tr>';
                }
                ?>
            </tbody>
        </table>
    </div>
</form>