<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="pt-BR"> 

	<head>
		
		
		<title>Meu controle - Auxiliando você a controlar seu dinheiro!</title>
	<meta charset="UTF-8"></head>

	<body style="width: 600px;height: 500px;">
	<hr style="margin-top: 20px;height: 7px;width: 800px;margin-left: 70px;background: lightsteelblue">  
	 <div style="margin-left: 100px;margin-top: 20px;font-size:25px;color: #76ab3b;font-family: arial; "><b> Cadastro - Meu Controle</b></div>
	          <hr style="margin-top: 2px;height: 7px;width: 800px;margin-left: 70px;background: lightsteelblue">            
						  <div style="margin-left: 100px;margin-top: 15px;font-size:25px;color:black;font-family: arial;">
						   Sr(a) <?= $this->nome ?> <?=$this->dados['ultimo_nome']?>,<p/>
                           Seja bem vindo ao meucontrole.com, para acessar o sistema utilize os dados a seguir. <br/>
                           Email: <?= $this->email?> <p/>
                           Senha: <?= $this->senha ?> <p/>
                                                  Obrigado<p/>
                         			   Equipe meucontrole.com
						   </div>
				
             <hr style="margin-top: 20px;height: 7px;width: 800px;margin-left: 70px;background: lightsteelblue">  
      </body>

</html>