

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-US"> 

	<head>
		
		<meta http-equiv="Content-type" content="text/html; charset=UTF-8" />
		<meta name="description" content="Template designed by Smartik" />
		<meta name="keywords" content="New, Line, Company, Smartik" />
		<meta name="author" content="Smartik" />
		
		<!--========= STYLES =========-->
		<link rel="stylesheet" href="<?= $this->baseUrl('css/reset.css')?>" />
		<link rel="stylesheet" href="<?= $this->baseUrl('css/grid_12.css')?>" />
		<link rel="stylesheet" href="<?= $this->baseUrl('css/colorbox.css')?>" />
		<link rel="stylesheet" href="<?= $this->baseUrl('css/uniform.default.css')?>">
		<link rel="stylesheet" href="<?= $this->baseUrl('css/chosen.css')?>">
		<link rel="stylesheet" href="<?= $this->baseUrl('css/style.css')?>" />
		<link rel="stylesheet" href="<?= $this->baseUrl('css/config.css')?>" />
		
		<!--============ JQUERY =============-->
		<script src="<?= $this->baseUrl('js/jquery.js')?>" type="text/javascript"></script>
		<script src="<?= $this->baseUrl('js/jquery.animate-colors-min.js')?>" type="text/javascript"></script>
		<script src="<?= $this->baseUrl('js/jquery.colorbox.js')?>" type="text/javascript"></script>
		<script src="<?= $this->baseUrl('js/jquery.easing.1.3.js')?>" type="text/javascript"></script>		
		<script src="<?= $this->baseUrl('js/jquery.uniform.js')?>" type="text/javascript"></script>
		<script src="<?= $this->baseUrl('js/chosen.jquery.js')?>" type="text/javascript"></script>
		<script src="<?= $this->baseUrl('js/cufon-yui.js')?>" type="text/javascript"></script>
		<script src="<?= $this->baseUrl('js/qlassik.cufonfonts.js')?>" type="text/javascript"></script>
		<script src="<?= $this->baseUrl('js/scripts_call_head.js')?>" type="text/javascript"></script>
						
		<!--=== ENABLE HTML5 TAGS FOR IE ===-->
		<!--[if IE]>
		<script src="js/html5.js"></script>
		<![endif]-->
		
		<title> </title>
	</head>

	<body>
		<header class="main_header">
			<section class="container">
				<div class="top">
<!--					<a class="logo" href="./index.html">Gestão de disponibilidade</a>-->
					<nav id="horizontal">
						<ul id="nav">
							<li><a href="<?=$this->baseUrl('/')?>">Inicio<span></span></a>
								<ul>
									<li><a href="./index.html">Home - Skitter Slider</a></li>
									<li><a href="./index_cycle.html">Home - Cycle Slider 1</a></li>
									<li><a href="./index_cycle2.html">Home - Cycle Slider 2</a></li>
									<li><a href="./index_cycle3.html">Home - Cycle Slider 3</a></li>
									<li><a href="./index_roundabout.html">Home - Roundabout Slider</a></li>
									<li><a href="./index_nivo.html">Home - Nivo Slider</a></li>
									
									<li><a href="./index_zaccordion.html">Home - zAccordion Slider</a></li>
								</ul>							
							</li>
							<li><a href="<?=$this->baseUrl('secretaria/')?>">Manutenção de Salas<span></span></a>
								
							</li>
							
							
							
						</ul>
					</nav><!-- End of menu -->
				</div>
			</section>
			<div class="border1"></div>
		</header>
		
		<section id="wrap">
			<div class="top_bg"></div>
			<section class="container layout">
				<div class="grid_12">
					<header class="page">
						<h1>Gestao de Disponibilidade </h1>
						</header>
				</div>
				<div class="clear"></div>
				<section class="single_page">	
					<?php  echo $this->layout()->content; ?>
				</section>
			
			</section> <!-- End section .container layout -->
		</section> <!-- End section #wrap -->
		
		<footer class="main_footer">
			
			<section class="mini_footer">
				<div class="container">
					<a class="logo_on_footer"></a>
					<nav id="ft_links">
						<ul id="nav_footer">
							<li><a href="#">Home</a></li>
							<li><a href="#">Cadastro de salas</a></li>
							
						</ul>
					</nav>
				</div>
			</section>
			<div class="border2"></div>
		</footer> <!-- End .main_footer -->
		
		<!-- JAVASCRIPTS -->
		<script src="<?=$this>baseUrl('js/scripts.js')?>" type="text/javascript"></script>
	</body>

</html>