<script type="text/javascript">
    $(document).ready(function(){
        <? foreach ($this->listaDisponibilidades as $value) :?>
                muda("<?=$value['hora'] . '-' . $value['dia']?>");
        <?endforeach;?>
    });
</script>

</div>
<script type="text/javascript">

    
    function gravaDados(id)
    {   
        if (id=="")
        {
            document.getElementById("txtHint").innerHTML="";
            return;
        }
        if (window.XMLHttpRequest)
        {// code for IE7+, Firefox, Chrome, Opera, Safari
            xmlhttp=new XMLHttpRequest();
        }
        else
        {// code for IE6, IE5
            xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
        }
        xmlhttp.onreadystatechange=function()
        {
            if (xmlhttp.readyState==4 && xmlhttp.status==200)
            {
                document.getElementById("resposta").innerHTML="Contato enviado com sucesso";
            }
        }
        xmlhttp.open("GET","<?= $this->baseUrl('professor/recebe-disponibilidade-aula/') ?>?id_usuario=<?= $this->id_usuario ?>&id="+id,true);
        xmlhttp.send();
   
        muda(id);
    }

    function muda(id){
        classe = document.getElementById(id).className;
        if(classe == 'branco'){
            document.getElementById(id).className = 'verde';
        }else{
            document.getElementById(id).className = 'branco';
        }
    }
</script>

<h2 align="center">Marque os horários que você tem disponíveis para lecionar</h2>
<table border="5"> 
    <tbody>
        <tr>
            <th width="14%" align="center"></th>
            <th width="14%" align="center"> Segunda</th>
            <th width="14%" align="center"> Terça</th>
            <th width="14%" align="center"> Quarta</th>
            <th width="14%" align="center"> Quinta</th>
            <th width="14%" align="center"> Sexta</th>
            <th width="14%" align="center"> Sábado</th>
        </tr>
        <tr>
            <th align="center"> 07:30</th>
            <td class="branco" title="07:30-segunda" onclick="gravaDados(this.id)" id="07:30-segunda" align="center"></td>
            <td class="branco" title="07:30-terca" onclick="gravaDados(this.id)" id="07:30-terca" align="center"></td>
            <td class="branco" title="07:30-quarta" onclick="gravaDados(this.id)" id="07:30-quarta" align="center"></td>
            <td class="branco" title="07:30-quinta" onclick="gravaDados(this.id)" id="07:30-quinta" align="center"></td>
            <td class="branco" title="07:30-sexta" onclick="gravaDados(this.id)" id="07:30-sexta" align="center"></td>
            <td class="branco" title="07:30-sabado" onclick="gravaDados(this.id)" id="07:30-sabado" align="center"></td>
        </tr>
        <tr>
            <th align="center"> 08:30</th>
            <td class="branco" title="08:30-segunda" onclick="gravaDados(this.id)" id="08:30-segunda" align="center"></td>
            <td class="branco" title="08:30-terca" onclick="gravaDados(this.id)" id="08:30-terca" align="center"></td>
            <td class="branco" title="08:30-quarta" onclick="gravaDados(this.id)" id="08:30-quarta" align="center"></td>
            <td class="branco" title="08:30-quinta" onclick="gravaDados(this.id)" id="08:30-quinta" align="center"></td>
            <td class="branco" title="08:30-sexta" onclick="gravaDados(this.id)" id="08:30-sexta" align="center"></td>
            <td class="branco" title="08:30-sabado" onclick="gravaDados(this.id)" id="08:30-sabado" align="center"></td>
        </tr>
        <tr>
            <th align="center"> 09:30</th>
            <td class="branco" title="09:30-segunda" onclick="gravaDados(this.id)" id="09:30-segunda" align="center"></td>
            <td class="branco" title="09:30-terca" onclick="gravaDados(this.id)" id="09:30-terca" align="center"></td>
            <td class="branco" title="09:30-quarta" onclick="gravaDados(this.id)" id="09:30-quarta" align="center"></td>
            <td class="branco" title="09:30-quinta" onclick="gravaDados(this.id)" id="09:30-quinta" align="center"></td>
            <td class="branco" title="09:30-sexta" onclick="gravaDados(this.id)" id="09:30-sexta" align="center"></td>
            <td class="branco" title="09:30-sabado" onclick="gravaDados(this.id)" id="09:30-sabado" align="center"></td>
        </tr>
        <tr>
            <th align="center"> 10:30</th>
            <td class="branco" title="10:30-segunda" onclick="gravaDados(this.id)" id="10:30-segunda" align="center"></td>
            <td class="branco" title="10:30-terca" onclick="gravaDados(this.id)" id="10:30-terca" align="center"></td>
            <td class="branco" title="10:30-quarta" onclick="gravaDados(this.id)" id="10:30-quarta" align="center"></td>
            <td class="branco" title="10:30-quinta" onclick="gravaDados(this.id)" id="10:30-quinta" align="center"></td>
            <td class="branco" title="10:30-sexta" onclick="gravaDados(this.id)" id="10:30-sexta" align="center"></td>
            <td class="branco" title="10:30-sabado" onclick="gravaDados(this.id)" id="10:30-sabado" align="center"></td>
        </tr>
        <tr>
            <th align="center"> 11:30</th>
            <td class="branco" title="11:30-sabado" onclick="gravaDados(this.id)" id="11:30-segunda" align="center"></td>
            <td class="branco" title="11:30-terca" onclick="gravaDados(this.id)" id="11:30-terca" align="center"></td>
            <td class="branco" title="11:30-quarta" onclick="gravaDados(this.id)" id="11:30-quarta" align="center"></td>
            <td class="branco" title="11:30-quinta" onclick="gravaDados(this.id)" id="11:30-quinta" align="center"></td>
            <td class="branco" title="11:30-sexta" onclick="gravaDados(this.id)" id="11:30-sexta" align="center"></td>
            <td class="branco" title="11:30-sabado" onclick="gravaDados(this.id)" id="11:30-sabado" align="center"></td>
        </tr>
        <tr>
            <th align="center"> 12:30</th>
            <td class="branco" title="11:30-sabado" onclick="gravaDados(this.id)" id="12:30-segunda" align="center"></td>
            <td class="branco" title="11:30-terca" onclick="gravaDados(this.id)" id="12:30-terca" align="center"></td>
            <td class="branco" title="11:30-quarta" onclick="gravaDados(this.id)" id="12:30-quarta" align="center"></td>
            <td class="branco" title="11:30-quinta" onclick="gravaDados(this.id)" id="12:30-quinta" align="center"></td>
            <td class="branco" title="11:30-sexta" onclick="gravaDados(this.id)" id="12:30-sexta" align="center"></td>
            <td class="branco" title="11:30-sabado" onclick="gravaDados(this.id)" id="12:30-sabado" align="center"></td>
        </tr>
        <tr>
            <th align="center"> 13:30</th>
            <td class="branco" title="13:30-segunda" onclick="gravaDados(this.id)" id="13:30-segunda" align="center"></td>
            <td class="branco" title="13:30-terca" onclick="gravaDados(this.id)" id="13:30-terca" align="center"></td>
            <td class="branco" title="13:30-quarta" onclick="gravaDados(this.id)" id="13:30-quarta" align="center"></td>
            <td class="branco" title="13:30-quinta" onclick="gravaDados(this.id)" id="13:30-quinta" align="center"></td>
            <td class="branco" title="13:30-sexta" onclick="gravaDados(this.id)" id="13:30-sexta" align="center"></td>
            <td class="branco" title="13:30-sabado" onclick="gravaDados(this.id)" id="13:30-sabado" align="center"></td>
        </tr>
        <tr>
            <th align="center"> 14:30</th>
            <td class="branco" title="14:30-segunda" onclick="gravaDados(this.id)" id="14:30-segunda" align="center"></td>
            <td class="branco" title="14:30-terca" onclick="gravaDados(this.id)" id="14:30-terca" align="center"></td>
            <td class="branco" title="14:30-quarta" onclick="gravaDados(this.id)" id="14:30-quarta" align="center"></td>
            <td class="branco" title="14:30-quinta" onclick="gravaDados(this.id)" id="14:30-quinta" align="center"></td>
            <td class="branco" title="14:30-sexta" onclick="gravaDados(this.id)" id="14:30-sexta" align="center"></td>
            <td class="branco" title="14:30-sabado" onclick="gravaDados(this.id)" id="14:30-sabado"align="center"></td>
        </tr>
        <tr>
            <th align="center"> 15:30</th>
            <td class="branco" title="15:30-segunda" onclick="gravaDados(this.id)" id="15:30-segunda" align="center"></td>
            <td class="branco" title="15:30-terca" onclick="gravaDados(this.id)" id="15:30-terca" align="center"></td>
            <td class="branco" title="15:30-quarta" onclick="gravaDados(this.id)" id="15:30-quarta" align="center"></td>
            <td class="branco" title="15:30-quinta" onclick="gravaDados(this.id)" id="15:30-quinta" align="center"></td>
            <td class="branco" title="15:30-sexta" onclick="gravaDados(this.id)" id="15:30-sexta" align="center"></td>
            <td class="branco" title="15:30-sabado" onclick="gravaDados(this.id)" id="15:30-sabado" align="center"></td>
        </tr>
        <tr>
            <th align="center"> 16:30</th>
            <td class="branco" title="16:30-segunda" onclick="gravaDados(this.id)" id="16:30-segunda" align="center"></td>
            <td class="branco" title="16:30-terca" onclick="gravaDados(this.id)" id="16:30-terca" align="center"></td>
            <td class="branco" title="16:30-quarta" onclick="gravaDados(this.id)" id="16:30-quarta" align="center"></td>
            <td class="branco" title="16:30-quinta" onclick="gravaDados(this.id)" id="16:30-quinta" align="center"></td>
            <td class="branco" title="16:30-sexta" onclick="gravaDados(this.id)" id="16:30-sexta" align="center"></td>
            <td class="branco" title="16:30-sabado" onclick="gravaDados(this.id)" id="16:30-sabado"align="center"></td>
        </tr>
        <tr>
            <th align="center"> 17:30</th>
            <td class="branco" title="17:30-segunda" onclick="gravaDados(this.id)" id="17:30-segunda" align="center"></td>
            <td class="branco" title="17:30-terca" onclick="gravaDados(this.id)" id="17:30-terca" align="center"></td>
            <td class="branco" title="17:30-quarta" onclick="gravaDados(this.id)" id="17:30-quarta" align="center"></td>
            <td class="branco" title="17:30-quinta" onclick="gravaDados(this.id)" id="17:30-quinta" align="center"></td>
            <td class="branco" title="17:30-sexta" onclick="gravaDados(this.id)" id="17:30-sexta" align="center"></td>
            <td class="branco" title="17:30-sabado" onclick="gravaDados(this.id)" id="17:30-sabado" align="center"></td>
        </tr>
        <tr>
            <th align="center"> 18:30</th>
            <td class="branco" title="18:30-segundo" onclick="gravaDados(this.id)" id="18:30-segunda" align="center"></td>
            <td class="branco" title="18:30-terca" onclick="gravaDados(this.id)" id="18:30-terca" align="center"></td>
            <td class="branco" title="18:30-quarta" onclick="gravaDados(this.id)" id="18:30-quarta" align="center"></td>
            <td class="branco" title="18:30-quinta" onclick="gravaDados(this.id)" id="18:30-quinta" align="center"></td>
            <td class="branco" title="1830-sexta" onclick="gravaDados(this.id)" id="18:30-sexta" align="center"></td>
            <td class="branco" title="18:30-sabado" onclick="gravaDados(this.id)" id="18:30-sabado" align="center"></td>
        </tr>
        <tr>
            <th align="center"> 19:30</th>
            <td class="branco" title="19:30-segunda" onclick="gravaDados(this.id)" id="19:30-segunda" align="center"></td>
            <td class="branco" title="19:30-terca" onclick="gravaDados(this.id)" id="19:30-terca" align="center"></td>
            <td class="branco" title="19:30-quarta" onclick="gravaDados(this.id)" id="19:30-quarta" align="center"></td>
            <td class="branco" title="19:30-quinta" onclick="gravaDados(this.id)" id="19:30-quinta" align="center"></td>
            <td class="branco" title="19:30-sexta" onclick="gravaDados(this.id)" id="19:30-sexta" align="center"></td>
            <td class="branco" title="19:30-sabado" onclick="gravaDados(this.id)" id="19:30-sabado" align="center"></td>
        </tr>
        <tr>
            <th align="center"> 20:30</th>
            <td class="branco" title="20:30-segunda" onclick="gravaDados(this.id)" id="20:30-segunda" align="center"></td>
            <td class="branco" title="20:30-terca" onclick="gravaDados(this.id)" id="20:30-terca" align="center"></td>
            <td class="branco" title="20:30-quarta" onclick="gravaDados(this.id)" id="20:30-quarta" align="center"></td>
            <td class="branco" title="20:30-quinta" onclick="gravaDados(this.id)" id="20:30-quinta" align="center"></td>
            <td class="branco" title="20:30-sexta" onclick="gravaDados(this.id)" id="20:30-sexta" align="center"></td>
            <td class="branco" title="20:30-sabado" onclick="gravaDados(this.id)" id="20:30-sabado" align="center"></td>
        </tr>
        <tr>
            <th align="center"> 21:30</th>
            <td class="branco" title="21:30-segunda" onclick="gravaDados(this.id)" id="21:30-segunda" align="center"></td>
            <td class="branco" title="21:30-terca" onclick="gravaDados(this.id)" id="21:30-terca" align="center"></td>
            <td class="branco" title="21:30-quarta" onclick="gravaDados(this.id)" id="21:30-quarta" align="center"></td>
            <td class="branco" title="21:30-quinta" onclick="gravaDados(this.id)" id="21:30-quinta" align="center"></td>
            <td class="branco" title="21:30-sexta" onclick="gravaDados(this.id)" id="21:30-sexta" align="center"></td>
            <td class="branco" title="21:30-sabado" onclick="gravaDados(this.id)" id="21:30-sabado" align="center"></td>
        </tr>
    </tbody>
</table>
