<div class=""><p><a href="<?= $this->baseUrl('/professor/cadastrar-professor/') ?>">Adicionar Professor</a></p></div>
<table class="style2"> 
    <thead> 
        <tr> 
            <th>Nome</th> 
            <th>Matricula</th>
            <th colspan="2">Ação</th>
        </tr> 
    </thead> 
    <? foreach ($this->listaProfessor as $item): ?> 
        <tbody> 
            <tr> 
                <td><?= $item->getNome() ?></td> 
                <td><?= $item->getMatricula() ?></td> 
                <td>
                    <a href="<?= $this->baseUrl('/professor/editar-professor/') ?><?= $item->getId_professor() ?>">Editar</a>
                </td>
                <td>
                    <a href="<?= $this->baseUrl('/professor/remover-professor/id_professor/') ?><?= $item->getId_professor() ?>">Remover</a>
                </td>
            </tr>
        </tbody>
    <? endforeach; ?>
</table>

