<nav id="horizontal">
    <ul id="nav">

        <li>
            <a href="<?= $this->baseUrl('login/sair/') ?>">Sair</a><span></span></a>
        </li>


    </ul>
</nav>
<table class="style2"> 
    <thead> 
        <tr> 
            <th>Código</th>
            <th>Nome</th>
            <th>Ementa</th>
 
        </tr> 
    </thead> 
    <tbody> 
        <? foreach ($this->listarTodos as $item): ?> 
            <tr> 

                <td><?= $item->getCodigo() ?></td>
                <td><?= $item->getNome() ?></td>
                <td><?= $item->getEmenta() ?></td>
            </tr>
        <? endforeach; ?>
    </tbody>
</table>