<h3>Area do professor</h3>
<table> 
						<thead> 
							<tr> 
								<th>Areas de interesse</th> 
								<th>Disciplinas de interesse</th> 
								<th>Meus dados</th> 
								<th>Minha agenda</th> 
								
							</tr> 
						</thead> 
						<tbody> 
							<tr> 
								<td>
                                                                    <a class="button blue small" href="<?=$this->baseUrl('usuario/perfil/id_usuario/1')?>">Visualizar</a>
                                                                    <a class="button red small" href="<?=$this->baseUrl('usuario/perfil/id_usuario/1')?>">Editar dados</a>
                                                                </td>
                                                                <td>
                                                                    <a class="button blue small" href="<?=$this->baseUrl('professor/perfil')?>">Visualizar</a>
                                                                    <a class="button red small" href="<?=$this->baseUrl('professor/editar-nivel-interesse')?>">Editar dados</a>
                                                                    <a class="button orange small" href="<?=$this->baseUrl('curso/listar-cursos')?>">Adicionar mais disciplinas</a>
                                                                    
                                                                </td>
                                                                <td>
                                                                    <a class="button blue small" href="<?=$this->baseUrl('usuario/perfil/id_usuario/1')?>">Visualizar</a>
                                                                    <a class="button red small" href="<?=$this->baseUrl('usuario/perfil/id_usuario/1')?>">Editar dados</a>
                                                                </td>
                                                                <td>
                                                                    <a class="button blue small" href="<?=$this->baseUrl('agenda/')?>">Visualizar</a>
                                                                    <a class="button orange small" href="<?=$this->baseUrl('agenda/cadastrar-evento')?>">Cadastrar evento</a>
                                                                </td>
								
								
							</tr> 
							
						</tbody>
					</table>